services:
  smooz-fetcher:
    build: .
    container_name: smooz-fetcher
    volumes:
      - ./app:/app/src
    dns:
      - 8.8.8.8

# services:
#   smooz-fetcher:
#     build: .
#     container_name: smooz-fetcher
#     dns:
#       - 8.8.8.8
#     restart: "no"
