services:
  smooz-fetcher:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smooz-fetcher
    volumes:
      - ./app:/app/src
    dns:
      - 8.8.8.8
    ports:
      - "8080:8080"

